### ISSUE TITLE
它的日志保存在哪里？我是否能后台运行时查看到消息日志？

### ISSUE THREAD

**Issue by ccProMax** [AlliotTech/chatgpt-web#1]
小白不太懂

**Comment by AlliotTech** [comment]
emmm  没做日志处理。。 直接丢控制台的。就临时写的一个玩具，

**Comment by AlliotTech** [comment]
你可以直接nohup
nohup gunicorn -w 4 -b 127.0.0.1:80 main:server --timeout 200 --worker-class gevent > log.txt 2>&1 &

**Comment by ccProMax** [comment]
> 你可以直接nohup nohup gunicorn -w 4 -b 127.0.0.1:80 main:server --timeout 200 --worker-class gevent > log.txt 2>&1 &

好的谢谢
